# Generated by Django 4.1.4 on 2022-12-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmCidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('dddCidade', models.CharField(max_length=2, verbose_name='DDD')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmEstado', models.CharField(max_length=100, verbose_name='Estado')),
                ('ufEstado', models.CharField(max_length=2, verbose_name='UF')),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmPonto', models.CharField(max_length=100, verbose_name='Ponto Turístico')),
                ('hrInicio', models.TimeField(verbose_name='Abertura')),
                ('hrfim', models.TimeField(verbose_name='Encerramento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor do Ingresso')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.estado'),
        ),
    ]
